# permissions for end users to edit adminbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adminbook-editor-role
rules:
- apiGroups:
  - webapp.tutorial.kubebuilder.io
  resources:
  - adminbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.tutorial.kubebuilder.io
  resources:
  - adminbooks/status
  verbs:
  - get
